root_pos: [0.0, 0.0, 0.6744]
root_ori: [0.0, 0.0, 0.0, 1.0]
dof_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
bone_mapping:
- [pelvis, left_hip, Trunk, Hip_Roll_Left]
- [left_hip, left_knee, Hip_Roll_Left, Shank_Left]
- [left_knee, left_ankle, Shank_Left, Ankle_Cross_Left]
- [pelvis, right_hip, Trunk, Hip_Roll_Right]
- [right_hip, right_knee, Hip_Roll_Right, Shank_Right]
- [right_knee, right_ankle, Shank_Right, Ankle_Cross_Right]
- [pelvis, left_shoulder, Trunk, AL3]
- [left_shoulder, left_elbow, AL3, left_hand_link]
- [left_elbow, left_wrist, left_hand_link, left_wrist_keypoint]
- [pelvis, right_shoulder, Trunk, AR3]
- [right_shoulder, right_elbow, AR3, right_hand_link]
- [right_elbow, right_wrist, right_hand_link, right_wrist_keypoint]
keypoints:
- {name: pelvis, body: Trunk}
- {name: left_hip_keypoint, body: Hip_Roll_Left}
- {name: left_knee_keypoint, body: Shank_Left}
- {name: left_ankle_keypoint, body: Ankle_Cross_Left}
- {name: left_heel_keypoint, body: left_heel_keypoint}
- {name: left_toe_keypoint, body: left_toe_keypoint}
- {name: right_hip_keypoint, body: Hip_Roll_Right}
- {name: right_knee_keypoint, body: Shank_Right}
- {name: right_ankle_keypoint, body: Ankle_Cross_Right}
- {name: right_heel_keypoint, body: right_heel_keypoint}
- {name: right_toe_keypoint, body: right_toe_keypoint}
- {name: torso_keypoint, body: Trunk}
- {name: left_shoulder_keypoint, body: AL3}
- {name: left_elbow_keypoint, body: left_hand_link}
- {name: left_wrist_keypoint, body: left_wrist_keypoint}
- {name: right_shoulder_keypoint, body: AR3}
- {name: right_elbow_keypoint, body: right_hand_link}
- {name: right_wrist_keypoint, body: right_wrist_keypoint}
body_names: [Trunk, H1, H2, AL1, AL2, AL3, left_hand_link, left_wrist_keypoint, AR1,
  AR2, AR3, right_hand_link, right_wrist_keypoint, Waist, Hip_Pitch_Left, Hip_Roll_Left,
  Hip_Yaw_Left, Shank_Left, Ankle_Cross_Left, left_foot_link, left_heel_keypoint,
  left_toe_keypoint, Hip_Pitch_Right, Hip_Roll_Right, Hip_Yaw_Right, Shank_Right,
  Ankle_Cross_Right, right_foot_link, right_heel_keypoint, right_toe_keypoint]
joint_names: [floating_base_joint, AAHead_yaw, Head_pitch, Left_Shoulder_Pitch, Left_Shoulder_Roll,
  Left_Elbow_Pitch, Left_Elbow_Yaw, Right_Shoulder_Pitch, Right_Shoulder_Roll, Right_Elbow_Pitch,
  Right_Elbow_Yaw, Waist, Left_Hip_Pitch, Left_Hip_Roll, Left_Hip_Yaw, Left_Knee_Pitch,
  Left_Ankle_Pitch, Left_Ankle_Roll, Right_Hip_Pitch, Right_Hip_Roll, Right_Hip_Yaw,
  Right_Knee_Pitch, Right_Ankle_Pitch, Right_Ankle_Roll]
joint_velocity_limits: [12.56, 12.56, 18.84, 18.84, 18.84, 18.84, 18.84, 18.84, 18.84,
  18.84, 10.88, 12.5, 10.9, 10.9, 11.7, 18.8, 12.4, 12.5, 10.9, 10.9, 11.7, 18.8, 12.4]
dof: [2, 2, 1, 1, 0, 1, 2, 1, 0, 1, 2, 2, 1, 0, 2, 1, 1, 0, 1, 0, 2, 1, 1, 0]
joint_axes:
- [0, 0, 1]
- [0.0, 0.0, 1.0]
- [0.0, 1.0, 0.0]
- [0.0, 1.0, 0.0]
- [1.0, 0.0, 0.0]
- [0.0, 1.0, 0.0]
- [0.0, 0.0, 1.0]
- [0.0, 1.0, 0.0]
- [1.0, 0.0, 0.0]
- [0.0, 1.0, 0.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 1.0, 0.0]
- [1.0, 0.0, 0.0]
- [0.0, 0.0, 1.0]
- [0.0, 1.0, 0.0]
- [0.0, 1.0, 0.0]
- [1.0, 0.0, 0.0]
- [0.0, 1.0, 0.0]
- [1.0, 0.0, 0.0]
- [0.0, 0.0, 1.0]
- [0.0, 1.0, 0.0]
- [0.0, 1.0, 0.0]
- [1.0, 0.0, 0.0]
